name: Deployment
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - run: |
        git log -n 1 master
        git pull origin master
        npm i
        npm run build --if-present
      working-directory: /var/www/gov-inventory-front-end
